import numpy as np

v1 = np.arange(10, 50)
v2 = np.arange(9).reshape(3, 3)
v3 = np.eye(3)
v4 = np.random.rand(3, 3, 3)
v5 = np.random.rand(10, 10)
v5_min = v5.min()
v5_max = v5.max()
v6 = np.random.rand(30)
v6_mean = v6.mean()
v7 = np.random.rand(5, 5)
v7_normalized = (v7 - np.mean(v7)) / np.std(v7)
a = np.random.rand(5, 3)
b = np.random.rand(3, 2)
product_ab = np.dot(a, b)
m1 = np.random.rand(3, 3)
m2 = np.random.rand(3, 3)
dot_product = np.dot(m1, m2)
m3 = np.random.rand(4, 4)
transpose_m3 = m3.T
m4 = np.random.rand(3, 3)
det_m4 = np.linalg.det(m4)
A = np.random.rand(3, 4)
B = np.random.rand(4, 3)
AB_product = np.dot(A, B)
M = np.random.rand(3, 3)
v = np.random.rand(3, 1)
Mv_product = np.dot(M, v)
A_sys = np.random.rand(3, 3)
b_sys = np.random.rand(3, 1)
x = np.linalg.solve(A_sys, b_sys)
M5 = np.random.rand(5, 5)
row_sums = M5.sum(axis=1)
col_sums = M5.sum(axis=0)
